MvcKutuphane/Controllers/PanelimController.cs
using MvcKutuphane.Models.Entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcKutuphane.Controllers
{
    [Authorize]
    public class PanelimController : Controller
    {
        // GET: Panelim
        DBKUTUPHANEEntities db = new DBKUTUPHANEEntities();
        [HttpGet]
        [Authorize]
        public ActionResult Index()
        
        
        {
            return View();
        }
        [HttpPost]
        public ActionResult Index(TBLUYELER p)
        {
            var kullanici = (string)Session["Mail"];
            var uye = db.TBLUYELER.FirstOrDefault(x => x.MAIL == kullanici);
            TempData["id"] = uye.ID;
            TempData["Soyad"] = uye.SOYAD;
            TempData["KAdi"] = uye.KULLANICIADI;
            TempData["Sifre"] = uye.SIFRE;
            TempData["Okul"] = uye.OKUL;
            TempData["Ad"] = uye.AD;

            uye.SIFRE = p.SIFRE;
            db.SaveChanges();
            return View();
        }
        public ActionResult Kitaplarim()
        {
            return View();
        }
    }
}

MvcKutuphane/Views/Panelim/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutPanelim.cshtml";
}

<h2>Burası Panel Sayfam</h2>
@using (Html.BeginForm("Index", "Panelim", FormMethod.Post))
{
    <table class="table table-hover">
        <tr>
            <td>

                <label style="font-weight:bolder">Öğrenci İd </label>   @TempData["id"].ToString()
            </td>
        </tr>
        <tr>
            <td>

                <label style="font-weight:bolder">Mail adresi: </label>   @HttpContext.Current.User.Identity.Name
            </td>
        </tr>
        <tr>
            @if (@TempData["Ad"] != null)
            {
                <td>
                    Ad:@TempData["Ad"].ToString()
                </td>
            }

        </tr>
        <tr>
            <td>
                Soyad: @TempData["Soyad"].ToString()
            </td>
        </tr>
        <tr>
            @if (@TempData["KAdi"] != null)
            {
                <td>
                    Kullanıcı Adı: @TempData["KAdi"].ToString()
                </td>
            }
        </tr>
        <tr>
            <td>
                <label style="font-weight:bolder"> Şifre: </label> <input type="text" class="form-control" value=" @TempData["Sifre"].ToString()" name="SIFRE" />
            </td>
        </tr>
        <tr>
            <td>
                Okul: @TempData["Okul"].ToString()
            </td>
        </tr>
        <tr>
            <td>
                <button class="btn btn-warning ">Şifre Güncelle</button>
            </td>
        </tr>
    </table>
}

MvcKutuphane/Views/Panelim/Kitaplarim.cshtml
@{
    ViewBag.Title = "Kitaplarim";
    Layout = "~/Views/Shared/_LayoutPanelim.cshtml";
}

<br/>

<h2>Kitaplarim</h2>

<br/>

<table class="table table-border">
    <tr>
        
        <th>Kitap Adı</th>
        <th>Alış Tarihi</th>
        <th>Üye İade tarihi</th>
        <th>Detaylar</th>
        
    </tr>
  
</table>